apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alx-test-application
spec:
  destination:
    namespace: 'default'
    server: 'https://kubernetes.default.svc'
  source:
    path: deploy/k8s
    repoURL: 'https://github.com/al3x3i/nodejs-api.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
